### ISSUE TITLE
Content tabs

### ISSUE THREAD

**Issue by leonardcser** [KyleKing/mdformat-admon#14]
Hi,

I've been using your plugin and it has been working great with Mkdocs and Material style admonitions. However, in my project I also use content tabs (https://squidfunk.github.io/mkdocs-material/reference/content-tabs) which are extremely similar to admonitions.

I've forked your repository and figured out that the only change would be to add `===` in the `MARKERS` tuple and corresponding tests. But, this made me realise that there would be so much code in common.

I am not sure how to approach this as you have already fully integrated this plugin and the name of does not really correspond to the content tabs. Do you have any suggestions or ideas? I would be more than happy to contribute.

**Comment by KyleKing** [comment]
That's a nice surprise that the admonition logic might just work!

So, I'm actually in the process of deleting that file now (#13) once my PR changes are released for the plugins package: https://github.com/executablebooks/mdit-py-plugins/pull/58

You could certainly implement just the parser in the same way I've included it here, but over the long-run, I would probably recommend:

- Reviewing other markdown implementations to see if something like content blocks are supported so that the plugin can be sufficiently generally. You can also look at the specs that I sampled for admonitions: https://github.com/KyleKing/mdformat-admon/tree/726262380659718b5d17cb9e9080858a7fa346f9#caveats
- Post an issue to https://github.com/executablebooks/mdit-py-plugins and let `chrisjsewell` know that you want to add support for content-tabs (hopefully I haven't added a can of worms by expanding the plugins to support `MKDocs` 😅)
- Open a PR against `mdit-py-plugins` that adds a new `content-block` plugin and extracts a set of shared utilities from the `admonitions` package (maybe these could be called `marked_blocks`?), which accept a list of `markers` and returns some sort of useful data structure or modifies the state directly

I think having a dedicated plugin in `mdit-py-plugins` that generates useful HTML would be the best approach, but that would be the hardest. In the interim, I would still probably recommend having a prototype version of the code in your package like I did before #13, so you can start to find edge cases before `mdit-py-plugins` is updated

Whichever approach you take, I would be happy to add your plugin to [`mdformat-mkdocs`](https://github.com/KyleKing/mdformat-mkdocs)!

I'm about to leave for vacation for over a week, so you caught me at a bad time, but hopefully this information is helpful! I'd be happy to add my input on code reviews or discuss other approaches as well

**Comment by KyleKing** [comment]
Also, to add, I'm not against supporting `content-blocks` in this plugin, but I agree that the plugin naming is unfortunate because it would be confusing to do both here

**Comment by leonardcser** [comment]
Hi Kyle,
Thanks a lot for the information. This is super helpful.

**Comment by KyleKing** [comment]
Turns out this was straightforward to implement!

There is now support for content-tabs in the latest version of `mdformat-admon>=1.1.0` :tada:

**Comment by KyleKing** [comment]
I've moved the Content Tab logic to https://github.com/KyleKing/mdformat-mkdocs#mdformat-mkdocs along with a number of other improvements that should make the feature more reliable

I can release v2.0.0 as soon as `mdformat-gfm` is released (https://github.com/hukkin/mdformat-gfm/issues/31), but in the meantime you can try out the improvements with:

```sh
pip install mdformat-mkdocs@git+https://github.com/KyleKing/mdformat-mkdocs.git
```
