### ISSUE TITLE
Support New GitHub Admonition Format

### ISSUE THREAD

**Issue by blink1073** [KyleKing/mdformat-admon#19]
GitHub has changed its admonition format, https://github.com/orgs/community/discussions/16925.

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.
```

Renders as

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

However, currently, it gets escaped by mdformat, even with this plugin installed.

```
> \[!NOTE\]  
> Highlights information that users should take into account, even when skimming.
```

**Comment by KyleKing** [comment]
Thanks for letting me know! I'll add official support when I have a chance

In the interim, you could try adding 'mdformat-wikilinks', which *may* prevent the brackets from being escaped

**Comment by blink1073** [comment]
Thanks!  Unfortunately that plugin did not prevent the escaping.

**Comment by KyleKing** [comment]
I'm starting a package to identify and format those alerts this weekend now that I'm back from a trip! (https://github.com/KyleKing/mdformat-gfm-alerts)

On a side-note, I've been following the community discussion, but I haven't come across an explanation from GitHub staff (`dipree`, `bestra`, etc.) on why they haven't adopted an existing syntax. I'm not sure if you have? I don't love having [yet another standard](https://xkcd.com/927), which makes more work for the OSS community (e.g. https://github.com/incentro-dc/remark-github-admonitions-to-directives, etc.) 😢

**Comment by blink1073** [comment]
I agree with your sentiments, and no I have not seen any other communication or reasoning other than the post I linked.  Thank you for taking on this feature!

**Comment by KyleKing** [comment]
Released 🎉 https://pypi.org/project/mdformat_gfm_alerts

Let me know if you find any issues or have follow up questions

**Comment by blink1073** [comment]
Works as advertised, thanks very much!

**Comment by jan-kouba** [comment]
Hi, will the `mdformat-gfm-alerts` package be included into the `mdformat-gfm` package eventually?

**Comment by KyleKing** [comment]
Hi @jan-kouba, the problem is philosophical that [`mdformat-gfm`](https://github.com/hukkin/mdformat-gfm?tab=readme-ov-file#description) implements the spec from [Github Flavored Markdown](https://github.github.com/gfm) ([and see](https://github.com/github/cmark-gfm/issues/350#issuecomment-1747789268)), while the Alerts are only documented on [Github's website](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).

I'm not sure what the future will hold. I've considered renaming `mdformat-gfm-alerts` into `mdformat-github` to philosophically align with the Github online docs, but there isn't enough technical clarity to build a formatter/renderer

**Comment by jan-kouba** [comment]
> Hi @jan-kouba, the problem is philosophical that [`mdformat-gfm`](https://github.com/hukkin/mdformat-gfm?tab=readme-ov-file#description) implements the spec from [Github Flavored Markdown](https://github.github.com/gfm) ([cmark-gfm](https://github.com/github/cmark-gfm) and [see](https://github.com/github/cmark-gfm/issues/350#issuecomment-1747789268)), while the Alerts are only documented on [Github's website](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#alerts).
> 
> I'm not sure what the future will hold. I've considered renaming `mdformat-gfm-alerts` into `mdformat-github` to philosophically align with the Github online docs, but there isn't enough technical clarity to build a formatter/renderer

Ok, clear, thanks!
